apiVersion: v1
kind: Secret
metadata:
  name: custom-ca-bundle
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  bundle-ca.crt: |
{{ .Files.Get "files/ca.crt" | b64enc | indent 4 }}
